// <auto-generated />
using System;
using GestaoSorveteria.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoSorveteria.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestaoSorveteria.Domain.Caixas.Caixa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AbertoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aberto_em");

                    b.Property<Guid>("AbertoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("aberto_por_usuario_id");

                    b.Property<decimal?>("Diferenca")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("diferenca");

                    b.Property<bool>("DivergenciaSincronizacao")
                        .HasColumnType("boolean")
                        .HasColumnName("divergencia_sincronizacao");

                    b.Property<DateTime?>("FechadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechado_em");

                    b.Property<Guid?>("FechadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("fechado_por_usuario_id");

                    b.Property<decimal>("FundoTroco")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("fundo_troco");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalVendasDinheiro")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_vendas_dinheiro");

                    b.Property<decimal?>("TotalVendasDinheiroApp")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_vendas_dinheiro_app");

                    b.Property<decimal?>("ValorContado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_contado");

                    b.Property<decimal?>("ValorEsperado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_esperado");

                    b.Property<decimal?>("ValorEsperadoApp")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_esperado_app");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_caixas");

                    b.HasIndex("AbertoEm")
                        .HasDatabaseName("ix_caixas_aberto_em");

                    b.HasIndex("AbertoPorUsuarioId")
                        .HasDatabaseName("ix_caixas_aberto_por_usuario_id");

                    b.HasIndex("FechadoPorUsuarioId")
                        .HasDatabaseName("ix_caixas_fechado_por_usuario_id");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("ux_caixas_unico_aberto")
                        .HasFilter("status = 'Aberto'");

                    b.ToTable("caixas", (string)null);
                });

            modelBuilder.Entity("GestaoSorveteria.Domain.Caixas.MovimentoCaixa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaixaId")
                        .HasColumnType("uuid")
                        .HasColumnName("caixa_id");

                    b.Property<DateTime>("Em")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("em");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_movimentos_caixa");

                    b.HasIndex("CaixaId")
                        .HasDatabaseName("ix_movimentos_caixa_caixa_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_movimentos_caixa_usuario_id");

                    b.ToTable("movimentos_caixa", (string)null);
                });

            modelBuilder.Entity("GestaoSorveteria.Domain.Comandas.Comanda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaixaId")
                        .HasColumnType("uuid")
                        .HasColumnName("caixa_id");

                    b.Property<DateTime?>("CanceladaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelada_em");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<DateTime?>("FechadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechada_em");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacao");

                    b.Property<bool>("RecebidaAposFechamentoCaixa")
                        .HasColumnType("boolean")
                        .HasColumnName("recebida_apos_fechamento_caixa");

                    b.Property<DateTime>("RecebidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recebida_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_comandas");

                    b.HasIndex("FechadaEm")
                        .HasDatabaseName("ix_comandas_fechada_em");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_comandas_status");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_comandas_usuario_id");

                    b.HasIndex("CaixaId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_comandas_caixa_id_numero");

                    b.ToTable("comandas", (string)null);
                });

            modelBuilder.Entity("GestaoSorveteria.Domain.Comandas.ItemComanda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comanda_id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("descricao");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<Guid?>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id")
                        .HasName("pk_itens_comanda");

                    b.HasIndex("ComandaId")
                        .HasDatabaseName("ix_itens_comanda_comanda_id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_itens_comanda_produto_id");

                    b.ToTable("itens_comanda", (string)null);
                });

            modelBuilder.Entity("GestaoSorveteria.Domain.Comandas.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comanda_id");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma");

                    b.Property<decimal>("Troco")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("troco");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor");

                    b.Property<decimal>("ValorRecebido")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_recebido");

                    b.HasKey("Id")
                        .HasName("pk_pagamentos");

                    b.HasIndex("ComandaId")
                        .HasDatabaseName("ix_pagamentos_comanda_id");

                    b.HasIndex("Forma")
                        .HasDatabaseName("ix_pagamentos_forma");

                    b.ToTable("pagamentos", (string)null);
                });

            modelBuilder.Entity("GestaoSorveteria.Domain.Produtos.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome_normalizado");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<bool>("PermiteValorLivre")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_valor_livre");

                    b.Property<decimal>("Preco")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("NomeNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ix_produtos_nome_normalizado");

                    b.HasIndex("Ativo", "Ordem")
                        .HasDatabaseName("ix_produtos_ativo_ordem");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("GestaoSorveteria.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_login");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("GestaoSorveteria.Domain.Caixas.Caixa", b =>
                {
                    b.HasOne("GestaoSorveteria.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AbertoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_caixas_usuarios_aberto_por_usuario_id");

                    b.HasOne("GestaoSorveteria.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("FechadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_caixas_usuarios_fechado_por_usuario_id");
                });

            modelBuilder.Entity("GestaoSorveteria.Domain.Caixas.MovimentoCaixa", b =>
                {
                    b.HasOne("GestaoSorveteria.Domain.Caixas.Caixa", null)
                        .WithMany("Movimentos")
                        .HasForeignKey("CaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimentos_caixa_caixas_caixa_id");

                    b.HasOne("GestaoSorveteria.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimentos_caixa_usuarios_usuario_id");
                });

            modelBuilder.Entity("GestaoSorveteria.Domain.Comandas.Comanda", b =>
                {
                    b.HasOne("GestaoSorveteria.Domain.Caixas.Caixa", null)
                        .WithMany()
                        .HasForeignKey("CaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comandas_caixas_caixa_id");

                    b.HasOne("GestaoSorveteria.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comandas_usuarios_usuario_id");
                });

            modelBuilder.Entity("GestaoSorveteria.Domain.Comandas.ItemComanda", b =>
                {
                    b.HasOne("GestaoSorveteria.Domain.Comandas.Comanda", null)
                        .WithMany("Itens")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_comanda_comandas_comanda_id");

                    b.HasOne("GestaoSorveteria.Domain.Produtos.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_itens_comanda_produtos_produto_id");
                });

            modelBuilder.Entity("GestaoSorveteria.Domain.Comandas.Pagamento", b =>
                {
                    b.HasOne("GestaoSorveteria.Domain.Comandas.Comanda", null)
                        .WithMany("Pagamentos")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagamentos_comandas_comanda_id");
                });

            modelBuilder.Entity("GestaoSorveteria.Domain.Caixas.Caixa", b =>
                {
                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("GestaoSorveteria.Domain.Comandas.Comanda", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
